# Numpy(넘파이)

In [1]:
import numpy

In [2]:
import numpy as np # 축약

a = np.array([1,2,3]) # 1차원 array [1,2,3] 생성
print(type(a))
print(a.shape) # 어떻게 생겼냐 (3,) ==> tuple 형태의 element 하나 => 크기가 3
print(a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0][0])
print(b[1, 0])

(2, 3)
1
4


In [10]:
import numpy as np
a = np.zeros((2,2)) # 모든 값이 0인 2x2 array 생성
print(a)
b = np.ones((1,2)) # 모든 값이 1인 1x2 array 생성
print(b)
c = np.full((2,2), 7) # 모든 값이 7인 2x2 array 생성
print(c)
d = np.eye(2) # 2x2 단위행렬(Identity matrix) 생성
print(d)
e = np.random.random((2,2)) # 0~1 랜덤 값을 가지는 2x2 array 생성
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.05122    0.34573381]
 [0.77395759 0.17153281]]


In [13]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

# 첫번째 행의 처음부터 2 앞까지 (0,1), 두번째 행에서
# 1부터 3 앞까지(1,2)의 값들을 떠와 b에 할당.
# 따라서 b는 다음과 같은 2x2 array:
# [[2 3]
#  [6 7]]

b = a[:2, 1:3]
print(b)
print(a[0,1])
b[0, 0] = 77
print(a[0, 1])

[[2 3]
 [6 7]]
2
77


In [16]:
import numpy as np
# 2차원 배열(3x4) 생성
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
# 두 번째 행의 값들을 모두 가져오는 두 가지 방법
#!!!!!!!!!!인덱싱 => 부분형태가 아닌 그 알맹이를 가져온다!
row_r1 = a[1, :]# 1차원 행렬 (4,)
#!!!!!!!!!!슬라이싱 => 잘라서 다시 그 형태를 유지해서 가져온다!
row_r2 = a[1:2, :] # 2차원 행렬 (1x4) – 기존 차원 유지
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
# 두 번째 열의 값들을 모두 가져오는 두 가지 방법
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape) # 벡터
print(col_r2, col_r2.shape) # 행렬의 개념인데 행이 1개 일뿐





[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [19]:
a = np.array([[1,2],[3,4],[5,6]])
c = np.array([a[0,0], a[1,1], a[2,0]])

c2 = a[[0,1,2], [0,1,0]]

# 이 둘은 같다 왼쪽은 x, 오른쪽은 y
print(c)
print(c2)

[1 4 5]
[1 4 5]


In [23]:
print(a[[0,0], [1,1]])
print(np.array([a[0,1],a[0,1]]))

[2 2]
[2 2]


In [28]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

print(a)

b = np.array([0, 2, 0 ,1])
print(a[np.arange(4), b]) # == np.array(range(4))

a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


# 데이터 타입


In [29]:
import numpy as np

x = np.array([1,2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int64
float64
int64


In [31]:
x = np.array([1,2], dtype= np.float64)
print(x)

[1. 2.]


## Array 연산

- 기본적으로 shape이 맞아야한다

In [32]:
import numpy as np

x = np.array([[1,2], [3,4]], dtype = np.float64)
y = np.array([[5,6], [7,8]], dtype = np.float64)

print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


## dot과 *의 차이

In [35]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v,w))
print(v*w)

print(x.dot(y))
print(np.dot(x, y))

219
219
[ 99 120]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# Sum

In [38]:
x = np.array([[1, 2],
              [3, 4]])
# print(x.shape)
print(np.sum(x, axis = 0).shape)
# print(np.sum(x, axis = 1).shape)
print(np.sum(x, axis = 2))
#axis 0이면 앞, 1이면 뒤를 없애는 방향으로 합이 일어난다

[3 7]


In [41]:
a = np.ones([2,3,4])
# print(a.shape)

print(np.sum(a))
print(np.sum(a, axis = 0)) 
# 2가 없어지고 3, 4가 남고 , 없어지는 애들의 합이 인자로 들어감
print(np.sum(a, axis = 1))
# print(np.sum(a, axis = 2))

24.0
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [45]:
import numpy as np

x = np.array([[1,2], [3, 4]])

print(x)
print(x.T)

# 벡터의 경우 같다.
v = np.array([1,2,3])
print(v.shape)
print(v.T.shape)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
(3,)
(3,)


# Broadcasting


In [48]:
x = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9], 
              [10,11,12]])

v = np.array([1,0,1])

# Broadcasting이 없었다면? - 1
# for는 연산속도에서 비효율적이다.

y = np.empty_like(x)
# shape은 tuple로 반환되므로
for i in range(x.shape[0]):
    y[i,:] = x[i,:] + v # y[i] = x[i] + y 도 됨
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [50]:
#Broadcasting이 없었다면? - 2
# 값복사로 인한 메모리 낭비가 있다.

x = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9], 
              [10,11,12]])
v = np.array([1,0,1])

vv = np.tile(v, (4,1)) # shape의 제일 뒤 숫자인 1을 주면 그걸 자신이라 생각

y = x+vv
print(y)



[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [53]:
#Broadcasting을 활용한다면?

y = x + v
print(y)

# 어떻게 알고 하는걸까?
print(x.shape)
print(v.shape)

#둘다 3은 같고 4가 남으니? 복사해서 더하면 되겠다

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
(4, 3)
(3,)


In [55]:
# 다른 예제

v1 = np.array([[1,0,1]])
y = x + v1

print(x.shape)
print(v1.shape)
print(y)

# 3은 중복이고 1을 반복하라는 소리구나? 라고 인식한다.
# (3,)에서도 맞는 이유는 뒤로부터 검사하기 때문에
# (4,3)과 (3,) 에서도 맞춰지는 것이다.

# (3, 4)와 (3, ) 는 안됨! 뒤로부터 맞춰보기 때문에

(4, 3)
(1, 3)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [56]:
# 되는 경우
# (4,3,2) (1,3,2)
# (2,1,3) (1,1,1)
# (3, 2, 1) (1, 2, 3)


# 안되는경우
# (4, 3) (2, 3) => 2니깐 2번 반복해라 이건 안됨
# (4, 3) (3, 3) => 이것도 안됨




In [60]:
x1 = x.T
v1 = np.array([1,0,1])
#되게하는 방법 (3,1)로만들면됨
# v1 = v1.reshape((3,1))
v2 = v1[:,None]
y = x1 + v2
print(x1.shape)
print(v2.shape)
print(y)

(3, 4)
(3, 1)
[[ 2  5  8 11]
 [ 2  5  8 11]
 [ 4  7 10 13]]


 - 연산자가 겹치는 경우 왼쪽부터 대부분 들어가나 연산자에 따라 다름

## 연습문제 2
 - 연립 2차 방정식 풀기
 - a+b=15 2a+b=25 a = 10, b = 5

In [ ]:
s1 = list(map(int, input('1번째 식: ').split(' ')))
s2 = list(map(int, input('2번째 식: ').split(' ')))

p = np.array([s1[:-1], s2[:-1]])
q = np.array([[s1[-1]], [s2[-1]]])

t = 1/(p[0, 0]*p[1, 1] - p[0, 1]*p[1, 0])
p1 = np.array([[p[1,1], p[0,1]*-1], [-1*p[1, 0], p[0,0]]])

print((t*p1).dot(q))

# pickle

- 데이터를 타입 변경 없이, 파일로 저장 및 불러오기가 가능하도록 하는 모듈